course_discovery/apps/publisher/api/urls.py
""" Publisher API URLs. """
from django.conf.urls import include, url

from course_discovery.apps.publisher.api.views import (
    AcceptAllRevisionView, ChangeCourseRunStateView, ChangeCourseStateView, CourseRevisionDetailView,
    CourseRoleAssignmentView, CoursesAutoComplete, OrganizationGroupUserView, RevertCourseRevisionView,
    UpdateCourseRunView
)

urlpatterns = [
    url(r'^course_role_assignments/(?P<pk>\d+)/$', CourseRoleAssignmentView.as_view(), name='course_role_assignments'),
    url(r'^admins/organizations/(?P<pk>\d+)/users/$', OrganizationGroupUserView.as_view(),
        name='organization_group_users'),
    url(r'^course_state/(?P<pk>\d+)/$', ChangeCourseStateView.as_view(), name='change_course_state'),
    url(r'^course_runs/(?P<pk>\d+)/$', UpdateCourseRunView.as_view(), name='update_course_run'),
    url(r'^course_revisions/(?P<history_id>\d+)/$', CourseRevisionDetailView.as_view(), name='course_revisions'),
    url(r'^course_run_state/(?P<pk>\d+)/$', ChangeCourseRunStateView.as_view(), name='change_course_run_state'),
    url(
        r'^course/revision/(?P<history_id>\d+)/revert/$',
        RevertCourseRevisionView.as_view(), name='course_revision_revert'
    ),
    url(r'^course-autocomplete/$', CoursesAutoComplete.as_view(), name='course-autocomplete'),
    url(
        r'^course/revision/(?P<history_id>\d+)/accept_revision/$',
        AcceptAllRevisionView.as_view(), name='accept_all_revision'
    ),
    url(r'^v1/', include('course_discovery.apps.publisher.api.v1.urls', namespace='v1')),
]

course_discovery/apps/publisher/api/v1/urls.py
from rest_framework.routers import DefaultRouter

from .views import CourseRunViewSet

router = DefaultRouter()
router.register(r'course_runs', CourseRunViewSet, base_name='course_run')
urlpatterns = router.urls

course_discovery/apps/publisher/urls.py
from django.conf.urls import include, url

from course_discovery.apps.publisher import views

urlpatterns = [
    url(r'^$', views.CourseRunListView.as_view(), name='publisher_dashboard'),
    url(r'^admin/importcourses/$', views.AdminImportCourse.as_view(), name='publisher_admin_import_course'),
    url(r'^api/', include('course_discovery.apps.publisher.api.urls', namespace='api')),
    url(r'^courses/$', views.CourseListView.as_view(), name='publisher_courses'),
    url(r'^courses/new/$', views.CreateCourseView.as_view(), name='publisher_courses_new'),
    url(r'^courses/(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='publisher_course_detail'),
    url(r'^courses/(?P<pk>\d+)/edit/$', views.CourseEditView.as_view(), name='publisher_courses_edit'),
    url(
        r'^courses/(?P<parent_course_id>\d+)/course_runs/new/$',
        views.CreateCourseRunView.as_view(),
        name='publisher_course_runs_new'
    ),
    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
    url(r'^course_runs/(?P<pk>\d+)/edit/$', views.CourseRunEditView.as_view(), name='publisher_course_runs_edit'),
    url(
        r'^course_runs/new/$',
        views.CreateRunFromDashboardView.as_view(),
        name='publisher_create_run_from_dashboard'
    ),
    url(
        r'^user/toggle/email_settings/$',
        views.ToggleEmailNotification.as_view(),
        name='publisher_toggle_email_settings'
    ),
    url(r'^courses/(?P<pk>\d+)/revisions/(?P<revision_id>\d+)/$', views.CourseRevisionView.as_view(),
        name='publisher_course_revision'),
    url(r'^email_preview/$', views.EmailPreviewView.as_view(), name='email_preview'),
]

course_discovery/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog

from course_discovery.apps.api.views import SwaggerSchemaView
from course_discovery.apps.core import views as core_views
from course_discovery.apps.course_metadata.views import QueryPreviewView

admin.site.site_header = _('Discovery Service Administration')
admin.site.site_title = admin.site.site_header
admin.autodiscover()

urlpatterns = auth_urlpatterns + [
    url(r'^admin/course_metadata/', include('course_discovery.apps.course_metadata.urls', namespace='admin_metadata')),
    url(r'^admin/core/', include('course_discovery.apps.core.urls', namespace='admin_core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('course_discovery.apps.api.urls', namespace='api')),
    # Use the same auth views for all logins, including those originating from the browseable API.
    url(r'^api-auth/', include(auth_urlpatterns, namespace='rest_framework')),
    url(r'^api-docs/', SwaggerSchemaView.as_view(), name='api_docs'),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^health/$', core_views.health, name='health'),
    url('^$', QueryPreviewView.as_view()),
    url(r'^publisher/', include('course_discovery.apps.publisher.urls', namespace='publisher')),
    url(r'^journal/', include('course_discovery.apps.journal.urls', namespace='journal')),
    url(
        r'^publisher/comments/', include(
            'course_discovery.apps.publisher_comments.urls', namespace='publisher_comments'
        )
    ),
    url(r'^language-tags/', include('course_discovery.apps.ietf_language_tags.urls', namespace='language_tags')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
]

# edx-drf-extensions csrf app
urlpatterns += [
    url(r'', include('csrf.urls')),
]

# Add the catalog extension urls if edx_catalog_extensions is installed.
if 'course_discovery.apps.edx_catalog_extensions' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^extensions/', include('course_discovery.apps.edx_catalog_extensions.urls', namespace='extensions'))
    )

if settings.DEBUG:  # pragma: no cover
    # We need this url pattern to serve user uploaded assets according to
    # https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    # This was modified to use LOCAL_MEDIA_URL to be able to server static files to external services like edx-mktg
    urlpatterns += static(settings.LOCAL_DISCOVERY_MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar

        urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

course_discovery/apps/publisher/api/v1/views.py
import logging
from collections import OrderedDict
from datetime import date

from edx_rest_api_client.client import EdxRestApiClient
from edx_rest_framework_extensions.auth.jwt.authentication import JwtAuthentication
from rest_framework import permissions, serializers, status, viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from slumber.exceptions import SlumberBaseException

from course_discovery.apps.core.utils import serialize_datetime
from course_discovery.apps.course_metadata.models import CourseEntitlement as DiscoveryCourseEntitlement
from course_discovery.apps.course_metadata.models import CourseRun as DiscoveryCourseRun
from course_discovery.apps.course_metadata.models import Seat as DiscoverySeat
from course_discovery.apps.course_metadata.models import Course, SeatType, Video
from course_discovery.apps.publisher.api.utils import (
    serialize_entitlement_for_ecommerce_api, serialize_seat_for_ecommerce_api
)
from course_discovery.apps.publisher.models import CourseRun, Seat
from course_discovery.apps.publisher.studio_api_utils import StudioAPI
from course_discovery.apps.publisher.utils import get_course_key

logger = logging.getLogger(__name__)


class CourseRunViewSet(viewsets.GenericViewSet):
    authentication_classes = (JwtAuthentication, SessionAuthentication,)
    queryset = CourseRun.objects.all()
    # NOTE: We intentionally use a basic serializer here since there is nothing, yet, to return.
    serializer_class = serializers.Serializer
    permission_classes = (permissions.IsAdminUser,)

    PUBLICATION_SUCCESS_STATUS = 'SUCCESS'

    @detail_route(methods=['post'])
    def publish(self, request, pk=None):
        course_run = self.get_object()
        partner = request.site.partner

        publication_status = {}

        try:
            publication_status['studio'] = self.publish_to_studio(partner, course_run)
            publication_status['discovery'] = self.publish_to_discovery(partner, course_run)
            # Publish to ecommerce last because it needs the just-created UUID from discovery
            publication_status['ecommerce'] = self.publish_to_ecommerce(partner, course_run)
        except SlumberBaseException as ex:
            logger.exception('Failed to publish course run [%s]!', pk)
            content = getattr(ex, 'content', None)
            if content:
                logger.error(content)
            raise

        status_code = status.HTTP_200_OK
        for _status in publication_status.values():
            if not _status.startswith(self.PUBLICATION_SUCCESS_STATUS):
                status_code = status.HTTP_502_BAD_GATEWAY
                break
        if status_code == status.HTTP_200_OK:
            logger.info(
                'Published course run with id: [%d] lms_course_id: [%s], user: [%s], date: [%s]',
                course_run.id,
                course_run.lms_course_id,
                request.user,
                date.today()
            )
        return Response(publication_status, status=status_code)

    def publish_to_studio(self, partner, course_run):
        api = StudioAPI(partner.studio_api_client)

        try:
            api.push_to_studio(course_run)
            return self.PUBLICATION_SUCCESS_STATUS
        except SlumberBaseException as ex:
            content = ex.content.decode('utf8')
            logger.exception('Failed to publish course run [%d] to Studio! Error was: [%s]', course_run.pk, content)
            return 'FAILED: ' + content
        except Exception as ex:  # pylint: disable=broad-except
            logger.exception('Failed to publish course run [%d] to Studio!', course_run.pk)
            return 'FAILED: ' + str(ex)

    def publish_to_ecommerce(self, partner, course_run):
        course_key = get_course_key(course_run.course)
        discovery_course = Course.objects.get(partner=partner, key=course_key)

        api = EdxRestApiClient(partner.ecommerce_api_url, jwt=partner.access_token)
        data = {
            'id': course_run.lms_course_id,
            'uuid': str(discovery_course.uuid),
            'name': course_run.title_override or course_run.course.title,
            'verification_deadline': serialize_datetime(course_run.end_date_temporary),
        }

        # NOTE: We only order here to aid testing. The E-Commerce API does NOT care about ordering.
        products = [serialize_seat_for_ecommerce_api(seat) for seat in
                    course_run.seats.exclude(type=Seat.CREDIT).order_by('created')]
        products.extend([serialize_entitlement_for_ecommerce_api(entitlement) for entitlement in
                         course_run.course.entitlements.order_by('created')])
        data['products'] = products

        try:
            api.publication.post(data)
            return self.PUBLICATION_SUCCESS_STATUS
        except SlumberBaseException as ex:
            content = ex.content.decode('utf8')
            logger.exception('Failed to publish course run [%d] to E-Commerce! Error was: [%s]', course_run.pk, content)
            return 'FAILED: ' + content

    def publish_to_discovery(self, partner, course_run):
        publisher_course = course_run.course
        course_key = get_course_key(publisher_course)

        video = None
        if publisher_course.video_link:
            video, __ = Video.objects.get_or_create(src=publisher_course.video_link)

        defaults = {
            'title': publisher_course.title,
            'short_description': publisher_course.short_description,
            'full_description': publisher_course.full_description,
            'level_type': publisher_course.level_type,
            'video': video,
            'outcome': publisher_course.expected_learnings,
            'prerequisites_raw': publisher_course.prerequisites,
            'syllabus_raw': publisher_course.syllabus,
            'additional_information': publisher_course.additional_information,
            'faq': publisher_course.faq,
            'learner_testimonials': publisher_course.learner_testimonial,
        }
        discovery_course, created = Course.objects.update_or_create(partner=partner, key=course_key, defaults=defaults)
        discovery_course.image.save(publisher_course.image.name, publisher_course.image.file)
        discovery_course.authoring_organizations.add(*publisher_course.organizations.all())

        subjects = [subject for subject in [
            publisher_course.primary_subject,
            publisher_course.secondary_subject,
            publisher_course.tertiary_subject
        ] if subject]
        subjects = list(OrderedDict.fromkeys(subjects))
        discovery_course.subjects.clear()
        discovery_course.subjects.add(*subjects)

        defaults = {
            'start': course_run.start_date_temporary,
            'end': course_run.end_date_temporary,
            'pacing_type': course_run.pacing_type_temporary,
            'title_override': course_run.title_override,
            'min_effort': course_run.min_effort,
            'max_effort': course_run.max_effort,
            'language': course_run.language,
            'weeks_to_complete': course_run.length,
            'has_ofac_restrictions': course_run.has_ofac_restrictions
        }
        discovery_course_run, __ = DiscoveryCourseRun.objects.update_or_create(
            course=discovery_course,
            key=course_run.lms_course_id,
            defaults=defaults
        )
        discovery_course_run.transcript_languages.add(*course_run.transcript_languages.all())
        discovery_course_run.staff.clear()
        discovery_course_run.staff.add(*course_run.staff.all())

        for entitlement in publisher_course.entitlements.all():
            DiscoveryCourseEntitlement.objects.update_or_create(
                course=discovery_course,
                mode=SeatType.objects.get(slug=entitlement.mode),
                defaults={
                    'partner': partner,
                    'price': entitlement.price,
                    'currency': entitlement.currency,
                }
            )

        for seat in course_run.seats.exclude(type=Seat.CREDIT).order_by('created'):
            DiscoverySeat.objects.update_or_create(
                course_run=discovery_course_run,
                type=seat.type,
                currency=seat.currency,
                defaults={
                    'price': seat.price,
                    'upgrade_deadline': seat.calculated_upgrade_deadline,
                }
            )
            if seat.masters_track:
                DiscoverySeat.objects.update_or_create(
                    course_run=discovery_course_run,
                    type=DiscoverySeat.MASTERS,
                    currency=seat.currency,
                    defaults={
                        'price': seat.price,
                        'upgrade_deadline': seat.calculated_upgrade_deadline,
                    }
                )

        if created:
            discovery_course.canonical_course_run = discovery_course_run
            discovery_course.save()

        return self.PUBLICATION_SUCCESS_STATUS

course_discovery/apps/publisher/templates/publisher/_clearImageLink.html
<div class="clear-image">
    <a class="remove-image" href="#">%(clear_checkbox_label)s</a>
    <div class="hidden">%(clear)s</div>
</div>

course_discovery/apps/publisher/templates/publisher/_clearableImageInput.html
<img class="course-image-thumbnail" src="%(initial_url)s">%(clear_template)s
<div class="course-image-input hidden">%(input)s</div>

course_discovery/apps/publisher/templates/publisher/_footer.html
{% load i18n %}
<div class="wrapper-footer wrapper">
    <footer class="primary">
        <div class="footer-content-primary">
          <div class="colophon">
            {% now "Y" as current_year %}
            <p>&copy; {{ current_year }} <a href="#" rel="external">{{ platform_name }}</a>.</p>
          </div>

            <nav class="nav-peripheral">
              <ol>
              <li class="nav-item nav-peripheral-tos">
                <a href="#">{% trans "Terms of Service" %}</a>
              </li>
              <li class="nav-item nav-peripheral-pp">
                <a href="#">{% trans "Privacy Policy" %}</a>
              </li>
              </ol>
            </nav>
        </div>

        <div class="footer-content-secondary" aria-label="{% trans 'Legal' %}">
          <div class="footer-about-copyright">
            <!--Site operators: Please do not remove this paragraph! This attributes back to edX and makes your acknowledgement of edX's trademarks clear.-->
            <p>
                <!--Translators: 'EdX', 'edX', 'Studio', and 'Open edX' are trademarks of 'edX Inc.'. Please do not translate any of these trademarks and company names.-->
                {% with link_start='<a data-rel="edx.org" href="https://www.edx.org/">' link_end='</a>' %}
                    {% blocktrans trimmed %}
                        EdX, Open edX, Publisher, and the edX and Open edX logos are registered trademarks or trademarks of {{link_start}}edX Inc.{{link_end}}
                    {% endblocktrans %}
                {% endwith %}
            </p>
          </div>

          <div class="footer-about-openedx">
            <a href="http://open.edx.org" title="{% trans 'Powered by Open edX' %}">
              <img alt="{% trans 'Powered by Open edX' %}" src="https://files.edx.org/openedx-logos/edx-openedx-logo-tag.png">
            </a>
          </div>
        </div>
    </footer>
</div>

course_discovery/apps/publisher/templates/publisher/_header.html
{% load static %}
{% load i18n %}
<header class="header">
    <div class="layout-1q1h1q layout-flush layout-header">
        <nav class="layout-col layout-col-a">
            <a href="{% url 'publisher:publisher_dashboard' %}">
                <img src="{% static 'images/logo.png' %}">
            </a>
        </nav>

        <main class="layout-col layout-col-b"></main>

        <aside class="layout-col layout-col-c">
            <nav class="nav-account" aria-label="{% trans 'Account' %}">
                <h2 class="sr-only">{% trans "Account Navigation" %}</h2>
                <ol>
                    <li class="nav-item nav-account-help">
                        <h3 class="title">
                            <span class="label">
                                <a href="https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/set_up_course/pub_create_ann_course/index.html" title="{% trans 'Contextual Online Help' %}" target="_blank">
                                    {% trans "Help" %}
                                </a>
                            </span>
                        </h3>
                    </li>
                    <li class="nav-item nav-account-user">
                        <h3 class="title">
                            <span class="label">
                                <a href="#" title="{{ user.username }}">{{ user.username|truncatechars:10 }}</a>
                            </span>
                            <span class="icon fa fa-caret-down"></span>
                        </h3>
                    </li>
                </ol>

                <div class="wrapper wrapper-nav-sub">
                    <div class="nav-sub">
                        <div class="nav-menu-item nav-email-notification">
                            <span class="email-switch-label"><b>{% trans "Email notifications" %}</b></span>
                            <label class="switch">
                                <input id="email-switch" type="checkbox" data-isEnabled="{{ is_email_notification_enabled }}" {% if is_email_notification_enabled %}checked{% endif %}>
                                <div class="slider"></div>
                            </label>
                            <span class="switch-label">{% if is_email_notification_enabled %} {% trans "ON" %} {% else %} {% trans "OFF" %} {% endif %}</span>
                        </div>
                        <div class="nav-menu-item nav-account-signout">
                            <a class="btn-neutral" href="/logout">{% trans "Sign Out" %}</a>
                        </div>
                    </div>
                </div>
            </nav>
        </aside>
    </div>
</header>

course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
<div class="instructor" id="instructor_{{ staff.id }}">
    <input type="hidden" id="staff_{{ staff.id }}" name="staff" value="{{ staff.id }}">
    <div><img src="{{ staff.get_profile_image_url }}"></div>
    <div><a class="delete" id="{{ staff.id }}" href="#"><i class="fa fa-trash-o fa-fw"></i></a>
        {% if course_user_role == 'course_team' %}
            {% if staff.position and staff.uuid and staff.position.organization_id in organizations_ids or staff.position.organization_id is None %}
                <a class="edit" id="{{ staff.uuid }}" href="#"><i class="fa fa-pencil-square-o fa-fw"></i></a>
            {% endif %}
        {% elif is_internal_user %}
            <a class="edit" id="{{ staff.uuid }}" href="#"><i class="fa fa-pencil-square-o fa-fw"></i></a>
        {% endif %}
        <b>{{ staff.full_name }}</b>
    </div>
</div>

course_discovery/apps/publisher/templates/publisher/_personLookup.html
<table class="instructor-option" id="{{ uuid }}" {% if can_edit_instructor %}  data-can-edit="{{ can_edit_instructor }}" {% endif %}>
  <tr>
    <td><img src="{{ profile_image }}" alt="profile image"/></td>
    <td>
      <b>{{ full_name }}</b>
      {% if position %}
        <p>{{ position }}</p>
        <span class="hidden">{{ organization_id }}</span>
      {% endif %}
    </td>
  </tr>
</table>
<hr>

course_discovery/apps/publisher/templates/publisher/_render_optional_field.html
{% load i18n %}

{% if field %}
  {{ field|safe }}
{% else %}
  <div class="dont-compare">{% trans "(Optional) Not yet added" %}</div>
{% endif %}

course_discovery/apps/publisher/templates/publisher/_render_required_field.html
{% load i18n %}

{% if field %}
  {{ field|safe }}
{% else %}
  <div class="dont-compare">{% trans "(Required) Not yet added" %}</div>
{% endif %}

course_discovery/apps/publisher/templates/publisher/course_list.html
{% extends 'publisher/base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
    {% trans "Courses" %}
{% endblock title %}

{% block page_content %}
    <h2 class="hd-2 course-count-heading"
        data-publisher-total-courses-count="{{publisher_total_courses_count}}"
        data-publisher-courses="{{courses}}"
        data-publisher-courses-url="{{publisher_courses_url}}"
        data-publisher-courses-allowed-page-sizes="{{allowed_page_sizes}}"
        >{{publisher_total_courses_count}} Courses</h2>
    <a href="{% url 'publisher:publisher_courses_new' %}" class="btn btn-brand btn-small btn-course-add">
        {% trans "Create New Course" %}
    </a>
    <div class="coursesTable">
        <table id="dataTableCourse" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th role="button">
                        {% trans "Course Name" %}
                    </th>
                    <th role="button">
                        {% trans "Course Number" %}
                    </th>
                    <th role="button">
                        {% trans "Organization" %}
                    </th>
                    <th role="button">
                        {% trans "Project Coordinator" %}
                    </th>
                    <th role="button">
                        {% trans "Runs" %}
                    </th>
                    <th role="button">
                        {% trans "Course Team Status" %}
                    </th>
                    <th role="button">
                        {% blocktrans with site_name=site_name trimmed %}{{ site_name }} Status{% endblocktrans %}
                    </th>
                    <th role="button">
                        {% trans "Last Handoff" %}
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/publisher/views/courses.js' %}"></script>
{% endblock %}

course_discovery/apps/publisher/templates/publisher/courserun_list.html
{% extends 'publisher/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Dashboard" %}
{% endblock title %}

{% block page_content %}
    <div class="about-and-add-buttons clearfix">
        <h2 class="hd-2 emphasized">{% trans "Course About Pages" %}</h2>
            <div class="col-60 float-left">
            <p class="about-publisher">{% trans "EdX Publisher is used to create course About pages. Users enter, review, and approve content in Publisher. Publisher keeps track of the details and sends email updates when actions are necessary." %}</p>
            <p>{% trans "EdX Publisher is a companion to edX Studio. Course teams enter About page information in Publisher, and course content in Studio." %}</p>
        </div>
        <div class="col-40 float-left">
            <a href="{% url 'publisher:publisher_courses_new' %}" class="btn btn-brand btn-add-course">
                {% trans "Add a New Course" %}
            </a>
            <a href="{% url 'publisher:publisher_create_run_from_dashboard' %}" class="btn btn-brand btn-add-courserun">
                {% trans "Add a Course Run" %}
            </a>
        </div>

    </div>
    <div class="publisher-container">
        {% with studio_count=studio_request_courses|length published_count=published_course_runs|length preview_count=preview_course_runs|length in_progress_count=in_progress_course_runs|length %}
        <h2 class="hd-2 emphasized course-runs-heading">{% trans "Course runs" %}</h2>
        <ul role="tablist" class="tabs">
            <li role="tab" id="tab-progress" class="tab" aria-selected="true" aria-expanded="false"
                    aria-controls="progress" tabindex="0">
                    <span>{{ in_progress_count }}</span>{% trans "In Development" %}
            </li>
            <li role="tab" id="tab-preview" class="tab" aria-selected="false" aria-expanded="false"
                aria-controls="preview" tabindex="-1">
                <span>{{ preview_count }}</span>{% trans "In Preview" %}
            </li>
            {% if is_project_coordinator %}
                <li role="tab" id="tab-studio" class="tab" aria-selected="false" aria-expanded="true"
                    aria-controls="studio" tabindex="-1" data-studio-count="{{ studio_count }}">
                    <span id="studio-count">{{ studio_count }}</span>{% trans "Studio Request" %}
                </li>
            {% endif %}
            <li role="tab" id="tab-published" class="tab" aria-selected="false" aria-expanded="false"
                aria-controls="published" tabindex="-1">
                <span>{{ published_count }}</span>{% trans "Published About Pages" %}
            </li>

        </ul>

        <div role="tabpanel" id="progress" class="tab-panel" aria-labelledby="tab-progress" aria-hidden="false" tabindex="-1">
             {% include "publisher/dashboard/_in_progress.html" %}
        </div>

        <div role="tabpanel" id="preview" class="tab-panel" aria-labelledby="tab-preview" aria-hidden="true" tabindex="-1">
            {% include "publisher/dashboard/_in_preview.html" %}
        </div>

        {% if is_project_coordinator %}
            <div role="tabpanel" id="studio" class="tab-panel" aria-labelledby="tab-studio" aria-hidden="false" tabindex="0">
                {% include "publisher/dashboard/_studio_requests.html" %}
            </div>
        {% endif %}

        <div role="tabpanel" id="published" class="tab-panel" aria-labelledby="tab-published" aria-hidden="false" tabindex="0">
            {% include "publisher/dashboard/_published.html" %}
        </div>
    </div>

    {% endwith %}
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/publisher/tabs.js' %}"></script>
    <script src="{% static 'js/publisher/views/courserun_list.js' %}"></script>
{% endblock %}

course_discovery/apps/publisher/templates/publisher/email_preview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Preview</title>
</head>
<body>

<h1>HTML</h1>
{{ html_content|safe }}

<h1>Text</h1>
<pre>
{{ text_content }}
</pre>

</body>
</html>

course_discovery/apps/publisher/templates/publisher/seat_form.html
{% extends 'publisher/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}
    {% trans "Seat Form" %}
{% endblock title %}

{% block page_content %}
    <div class="layout-full layout publisher-layout">
        <div class="publisher-container">
            <div class="course-information">
                <h4 class="hd-4">{% trans "Seat Form" %}</h4>
                <form class="form" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {% for field in form %}
                            {% include "publisher/form_field.html" %}
                        {% endfor %}
                    </fieldset>
                    <button class="btn-brand btn-base" type="submit">{% trans "Save" %}</button>
                </form>
            </div>
            <div class="comment-container">
                {% include 'publisher/comments/comments_list.html' %}
                {% include 'publisher/comments/add_auth_comments.html' %}
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/publisher/seat-type-change.js' %}"></script>
{% endblock %}