course_discovery/apps/publisher/api/urls.py
""" Publisher API URLs. """
from django.conf.urls import include, url

from course_discovery.apps.publisher.api.views import (
    AcceptAllRevisionView, ChangeCourseRunStateView, ChangeCourseStateView, CourseRevisionDetailView,
    CourseRoleAssignmentView, CoursesAutoComplete, OrganizationGroupUserView, RevertCourseRevisionView,
    UpdateCourseRunView
)

urlpatterns = [
    url(r'^course_role_assignments/(?P<pk>\d+)/$', CourseRoleAssignmentView.as_view(), name='course_role_assignments'),
    url(r'^admins/organizations/(?P<pk>\d+)/users/$', OrganizationGroupUserView.as_view(),
        name='organization_group_users'),
    url(r'^course_state/(?P<pk>\d+)/$', ChangeCourseStateView.as_view(), name='change_course_state'),
    url(r'^course_runs/(?P<pk>\d+)/$', UpdateCourseRunView.as_view(), name='update_course_run'),
    url(r'^course_revisions/(?P<history_id>\d+)/$', CourseRevisionDetailView.as_view(), name='course_revisions'),
    url(r'^course_run_state/(?P<pk>\d+)/$', ChangeCourseRunStateView.as_view(), name='change_course_run_state'),
    url(
        r'^course/revision/(?P<history_id>\d+)/revert/$',
        RevertCourseRevisionView.as_view(), name='course_revision_revert'
    ),
    url(r'^course-autocomplete/$', CoursesAutoComplete.as_view(), name='course-autocomplete'),
    url(
        r'^course/revision/(?P<history_id>\d+)/accept_revision/$',
        AcceptAllRevisionView.as_view(), name='accept_all_revision'
    ),
    url(r'^v1/', include('course_discovery.apps.publisher.api.v1.urls', namespace='v1')),
]

course_discovery/apps/publisher/api/v1/urls.py
from rest_framework.routers import DefaultRouter

from .views import CourseRunViewSet

router = DefaultRouter()
router.register(r'course_runs', CourseRunViewSet, base_name='course_run')
urlpatterns = router.urls

course_discovery/apps/publisher/urls.py
from django.conf.urls import include, url

from course_discovery.apps.publisher import views

urlpatterns = [
    url(r'^$', views.CourseRunListView.as_view(), name='publisher_dashboard'),
    url(r'^admin/importcourses/$', views.AdminImportCourse.as_view(), name='publisher_admin_import_course'),
    url(r'^api/', include('course_discovery.apps.publisher.api.urls', namespace='api')),
    url(r'^courses/$', views.CourseListView.as_view(), name='publisher_courses'),
    url(r'^courses/new/$', views.CreateCourseView.as_view(), name='publisher_courses_new'),
    url(r'^courses/(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='publisher_course_detail'),
    url(r'^courses/(?P<pk>\d+)/edit/$', views.CourseEditView.as_view(), name='publisher_courses_edit'),
    url(
        r'^courses/(?P<parent_course_id>\d+)/course_runs/new/$',
        views.CreateCourseRunView.as_view(),
        name='publisher_course_runs_new'
    ),
    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
    url(r'^course_runs/(?P<pk>\d+)/edit/$', views.CourseRunEditView.as_view(), name='publisher_course_runs_edit'),
    url(
        r'^course_runs/new/$',
        views.CreateRunFromDashboardView.as_view(),
        name='publisher_create_run_from_dashboard'
    ),
    url(
        r'^user/toggle/email_settings/$',
        views.ToggleEmailNotification.as_view(),
        name='publisher_toggle_email_settings'
    ),
    url(r'^courses/(?P<pk>\d+)/revisions/(?P<revision_id>\d+)/$', views.CourseRevisionView.as_view(),
        name='publisher_course_revision'),
    url(r'^email_preview/$', views.EmailPreviewView.as_view(), name='email_preview'),
]

course_discovery/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog

from course_discovery.apps.api.views import SwaggerSchemaView
from course_discovery.apps.core import views as core_views
from course_discovery.apps.course_metadata.views import QueryPreviewView

admin.site.site_header = _('Discovery Service Administration')
admin.site.site_title = admin.site.site_header
admin.autodiscover()

urlpatterns = auth_urlpatterns + [
    url(r'^admin/course_metadata/', include('course_discovery.apps.course_metadata.urls', namespace='admin_metadata')),
    url(r'^admin/core/', include('course_discovery.apps.core.urls', namespace='admin_core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('course_discovery.apps.api.urls', namespace='api')),
    # Use the same auth views for all logins, including those originating from the browseable API.
    url(r'^api-auth/', include(auth_urlpatterns, namespace='rest_framework')),
    url(r'^api-docs/', SwaggerSchemaView.as_view(), name='api_docs'),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^health/$', core_views.health, name='health'),
    url('^$', QueryPreviewView.as_view()),
    url(r'^publisher/', include('course_discovery.apps.publisher.urls', namespace='publisher')),
    url(r'^journal/', include('course_discovery.apps.journal.urls', namespace='journal')),
    url(
        r'^publisher/comments/', include(
            'course_discovery.apps.publisher_comments.urls', namespace='publisher_comments'
        )
    ),
    url(r'^language-tags/', include('course_discovery.apps.ietf_language_tags.urls', namespace='language_tags')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
]

# edx-drf-extensions csrf app
urlpatterns += [
    url(r'', include('csrf.urls')),
]

# Add the catalog extension urls if edx_catalog_extensions is installed.
if 'course_discovery.apps.edx_catalog_extensions' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^extensions/', include('course_discovery.apps.edx_catalog_extensions.urls', namespace='extensions'))
    )

if settings.DEBUG:  # pragma: no cover
    # We need this url pattern to serve user uploaded assets according to
    # https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    # This was modified to use LOCAL_MEDIA_URL to be able to server static files to external services like edx-mktg
    urlpatterns += static(settings.LOCAL_DISCOVERY_MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar

        urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

course_discovery/apps/publisher/api/v1/views.py
import logging
from collections import OrderedDict
from datetime import date

from edx_rest_api_client.client import EdxRestApiClient
from edx_rest_framework_extensions.auth.jwt.authentication import JwtAuthentication
from rest_framework import permissions, serializers, status, viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from slumber.exceptions import SlumberBaseException

from course_discovery.apps.core.utils import serialize_datetime
from course_discovery.apps.course_metadata.models import CourseEntitlement as DiscoveryCourseEntitlement
from course_discovery.apps.course_metadata.models import CourseRun as DiscoveryCourseRun
from course_discovery.apps.course_metadata.models import Seat as DiscoverySeat
from course_discovery.apps.course_metadata.models import Course, SeatType, Video
from course_discovery.apps.publisher.api.utils import (
    serialize_entitlement_for_ecommerce_api, serialize_seat_for_ecommerce_api
)
from course_discovery.apps.publisher.models import CourseRun, Seat
from course_discovery.apps.publisher.studio_api_utils import StudioAPI
from course_discovery.apps.publisher.utils import get_course_key

logger = logging.getLogger(__name__)


class CourseRunViewSet(viewsets.GenericViewSet):
    authentication_classes = (JwtAuthentication, SessionAuthentication,)
    queryset = CourseRun.objects.all()
    # NOTE: We intentionally use a basic serializer here since there is nothing, yet, to return.
    serializer_class = serializers.Serializer
    permission_classes = (permissions.IsAdminUser,)

    PUBLICATION_SUCCESS_STATUS = 'SUCCESS'

    @detail_route(methods=['post'])
    def publish(self, request, pk=None):
        course_run = self.get_object()
        partner = request.site.partner

        publication_status = {}

        try:
            publication_status['studio'] = self.publish_to_studio(partner, course_run)
            publication_status['discovery'] = self.publish_to_discovery(partner, course_run)
            # Publish to ecommerce last because it needs the just-created UUID from discovery
            publication_status['ecommerce'] = self.publish_to_ecommerce(partner, course_run)
        except SlumberBaseException as ex:
            logger.exception('Failed to publish course run [%s]!', pk)
            content = getattr(ex, 'content', None)
            if content:
                logger.error(content)
            raise

        status_code = status.HTTP_200_OK
        for _status in publication_status.values():
            if not _status.startswith(self.PUBLICATION_SUCCESS_STATUS):
                status_code = status.HTTP_502_BAD_GATEWAY
                break
        if status_code == status.HTTP_200_OK:
            logger.info(
                'Published course run with id: [%d] lms_course_id: [%s], user: [%s], date: [%s]',
                course_run.id,
                course_run.lms_course_id,
                request.user,
                date.today()
            )
        return Response(publication_status, status=status_code)

    def publish_to_studio(self, partner, course_run):
        api = StudioAPI(partner.studio_api_client)

        try:
            api.push_to_studio(course_run)
            return self.PUBLICATION_SUCCESS_STATUS
        except SlumberBaseException as ex:
            content = ex.content.decode('utf8')
            logger.exception('Failed to publish course run [%d] to Studio! Error was: [%s]', course_run.pk, content)
            return 'FAILED: ' + content
        except Exception as ex:  # pylint: disable=broad-except
            logger.exception('Failed to publish course run [%d] to Studio!', course_run.pk)
            return 'FAILED: ' + str(ex)

    def publish_to_ecommerce(self, partner, course_run):
        course_key = get_course_key(course_run.course)
        discovery_course = Course.objects.get(partner=partner, key=course_key)

        api = EdxRestApiClient(partner.ecommerce_api_url, jwt=partner.access_token)
        data = {
            'id': course_run.lms_course_id,
            'uuid': str(discovery_course.uuid),
            'name': course_run.title_override or course_run.course.title,
            'verification_deadline': serialize_datetime(course_run.end_date_temporary),
        }

        # NOTE: We only order here to aid testing. The E-Commerce API does NOT care about ordering.
        products = [serialize_seat_for_ecommerce_api(seat) for seat in
                    course_run.seats.exclude(type=Seat.CREDIT).order_by('created')]
        products.extend([serialize_entitlement_for_ecommerce_api(entitlement) for entitlement in
                         course_run.course.entitlements.order_by('created')])
        data['products'] = products

        try:
            api.publication.post(data)
            return self.PUBLICATION_SUCCESS_STATUS
        except SlumberBaseException as ex:
            content = ex.content.decode('utf8')
            logger.exception('Failed to publish course run [%d] to E-Commerce! Error was: [%s]', course_run.pk, content)
            return 'FAILED: ' + content

    def publish_to_discovery(self, partner, course_run):
        publisher_course = course_run.course
        course_key = get_course_key(publisher_course)

        video = None
        if publisher_course.video_link:
            video, __ = Video.objects.get_or_create(src=publisher_course.video_link)

        defaults = {
            'title': publisher_course.title,
            'short_description': publisher_course.short_description,
            'full_description': publisher_course.full_description,
            'level_type': publisher_course.level_type,
            'video': video,
            'outcome': publisher_course.expected_learnings,
            'prerequisites_raw': publisher_course.prerequisites,
            'syllabus_raw': publisher_course.syllabus,
            'additional_information': publisher_course.additional_information,
            'faq': publisher_course.faq,
            'learner_testimonials': publisher_course.learner_testimonial,
        }
        discovery_course, created = Course.objects.update_or_create(partner=partner, key=course_key, defaults=defaults)
        discovery_course.image.save(publisher_course.image.name, publisher_course.image.file)
        discovery_course.authoring_organizations.add(*publisher_course.organizations.all())

        subjects = [subject for subject in [
            publisher_course.primary_subject,
            publisher_course.secondary_subject,
            publisher_course.tertiary_subject
        ] if subject]
        subjects = list(OrderedDict.fromkeys(subjects))
        discovery_course.subjects.clear()
        discovery_course.subjects.add(*subjects)

        defaults = {
            'start': course_run.start_date_temporary,
            'end': course_run.end_date_temporary,
            'pacing_type': course_run.pacing_type_temporary,
            'title_override': course_run.title_override,
            'min_effort': course_run.min_effort,
            'max_effort': course_run.max_effort,
            'language': course_run.language,
            'weeks_to_complete': course_run.length,
            'has_ofac_restrictions': course_run.has_ofac_restrictions
        }
        discovery_course_run, __ = DiscoveryCourseRun.objects.update_or_create(
            course=discovery_course,
            key=course_run.lms_course_id,
            defaults=defaults
        )
        discovery_course_run.transcript_languages.add(*course_run.transcript_languages.all())
        discovery_course_run.staff.clear()
        discovery_course_run.staff.add(*course_run.staff.all())

        for entitlement in publisher_course.entitlements.all():
            DiscoveryCourseEntitlement.objects.update_or_create(
                course=discovery_course,
                mode=SeatType.objects.get(slug=entitlement.mode),
                defaults={
                    'partner': partner,
                    'price': entitlement.price,
                    'currency': entitlement.currency,
                }
            )

        for seat in course_run.seats.exclude(type=Seat.CREDIT).order_by('created'):
            DiscoverySeat.objects.update_or_create(
                course_run=discovery_course_run,
                type=seat.type,
                currency=seat.currency,
                defaults={
                    'price': seat.price,
                    'upgrade_deadline': seat.calculated_upgrade_deadline,
                }
            )
            if seat.masters_track:
                DiscoverySeat.objects.update_or_create(
                    course_run=discovery_course_run,
                    type=DiscoverySeat.MASTERS,
                    currency=seat.currency,
                    defaults={
                        'price': seat.price,
                        'upgrade_deadline': seat.calculated_upgrade_deadline,
                    }
                )

        if created:
            discovery_course.canonical_course_run = discovery_course_run
            discovery_course.save()

        return self.PUBLICATION_SUCCESS_STATUS

course_discovery/apps/publisher/templates/publisher/course_run_detail/_all.html
{% load i18n %}

<div class="course-information" xmlns="http://www.w3.org/1999/html">

  <div class="info-item">
    <div class="heading">
      {% trans "Studio URL" %}
    </div>
    <div>
      {% if course_run.studio_url %}
        <a target="_blank" href="{{ course_run.studio_url }}">{{ course_run.lms_course_id }}</a>
      {% else %}
        {% trans "(Required) To be added by edX" %}
      {% endif %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Start Date (time in UTC)" %}
    </div>
    <div>{{ course_run.start_date_temporary }}</div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "End Date (time in UTC)" %}
    </div>
    <div>{{ course_run.end_date_temporary }}</div>
  </div>

  {% if is_seat_version %}
    <div class="info-item">
      <div class="heading">
        {% trans "Enrollment Track" %}
      </div>
      <div>{{ course_run.course_type }}</div>
    </div>

      {% if course_run.seat_price %}
        <div class="info-item">
          <div class="heading">
            {% trans "Certificate Price" %}
          </div>
          <div>
              ${{ course_run.seat_price }}
          </div>
        </div>
      {% endif %}

      {% if course_run.credit_seat_price %}
        <div class="info-item">
          <div class="heading">
            {% trans "Credit Price" %}
          </div>
          <div>
              ${{ course_run.credit_seat_price }}
          </div>
        </div>
      {% endif %}
  {% endif %}

  <div class="info-item">
    <div class="heading">
      {% trans "Course Staff" %}
    </div>
    <div>
      {% if not course_run.course_staff %}
        {% trans "(Required) Not yet added" %}
      {% else %}
        {% for obj in course_run.course_staff %}
          <div class="course-staff">
            <img src="{{ obj.image_url }}" alt=""/>

            <div class="staff-detail">
              <div class="name">
                  <a href="#" class="btn-instructor-detail"  data-staff_id="{{ obj.uuid }}">{{ obj.full_name }}</a>
              </div>
              <div>{{ obj.position }}</div>
              <div class="organization">{{ obj.organization }}</div>
            </div>
          </div>
          <div class="clearfix"></div>
        {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Estimated Effort" %}
    </div>
    <div>
      {% if course_run.min_effort and course_run.max_effort %}
        {{ course_run.min_effort }}-{{ course_run.max_effort }} {% trans "hours per week" %}
      {% elif course_run.min_effort %}
        {{ course_run.min_effort }} {% trans "hours per week" %}
      {% else %}
        {% with  course_run.estimated_effort as field %}
            {% include "publisher/_render_required_field.html" %}
        {% endwith %}
      {% endif %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Course Content Language" %}
    </div>
    <div>
      {% with  course_run.language.name as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Video Transcript Language" %}
    </div>
    <div>
      {% with  course_run.transcript_languages as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Course Video Language" %}
    </div>
    <div>
      {% with  course_run.video_language as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Course Length (Weeks)" %}
    </div>
    <div>
      {% with  course_run.length as field %}
        {% include "publisher/_render_required_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Has OFAC Restriction text" %}
    </div>
    <div>
      {% with  course_run.has_ofac_restrictions as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "MicroMasters Program Name" %}
    </div>
    <div>
      {% with  course_run.micromasters_name as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "XSeries Program Name" %}
    </div>
    <div>
      {% with  course_run.xseries_name as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

  <div class="info-item">
    <div class="heading">
      {% trans "Professional Certificate Program Name" %}
    </div>
    <div>
      {% with  course_run.professional_certificate_name as field %}
        {% include "publisher/_render_optional_field.html" %}
      {% endwith %}
    </div>
  </div>

</div>
<div class="clearfix"></div>
<script type="text/javascript">
    var staffData = {{ course_staff_config | safe }};
</script>

course_discovery/apps/publisher/templates/publisher/course_run_detail/_cat.html
{% load i18n %}
{% block content %}

   <div class="course-information">
        <div class="info-item">
            <div class="heading">
                {% trans "Course ID" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy">
              {% with  course_run.lms_course_id as field %}
                {% include "publisher/_render_required_field.html" %}
              {% endwith %}
            </div>
        </div>
        <div class="info-item">
            <div class="heading">
                {% trans "Enrollment Types" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy">{{ course_run.course_type|capfirst }}</div>
        </div>
    </div>



    {% include 'publisher/course_run_detail/_seats.html' %}
    {% include 'publisher/course_run_detail/_credit_seat.html' %}

    <div class="clearfix"></div>

{% endblock %}

course_discovery/apps/publisher/templates/publisher/course_run_detail/_clipboard.html
<button class="btn btn-small btn-copy" title="Copy to clipboard" aria-label="Copy to clipboard">
    <span class="icon fa fa-copy" aria-hidden="true"></span>
</button>

course_discovery/apps/publisher/templates/publisher/course_run_detail/_credit_seat.html
{% load i18n %}
<h3 class="hd-6 seat-set-hd">{% trans "Credit Seats" %}</h3>
{% if course_run.credit_seat %}
<div class="seat-set">
<table class="table">
    <tr>
        <th scope="col">{% trans "Credit Provider" %}</th>
        <th scope="col">{% trans "Price" %}</th>
        <th scope="col">{% trans "Currency" %}</th>
        <th scope="col">{% trans "Credit Hours" %}</th>
        <th scope="col">{% trans "Upgrade Deadline (time in UTC)" %}</th>
    </tr>
    <tr>
        <td>{{ course_run.credit_seat.credit_provider}}</td>
        <td>{{ course_run.credit_seat.price}}</td>
        <td>{{ course_run.credit_seat.currency.name}}</td>
        <td>{{ course_run.credit_seat.credit_hours }}</td>
        <td>{{ course_run.credit_seat.upgrade_deadline }}</td>
    </tr>

</table>
</div>
{% else %}
   {% trans "(Optional) Not yet added" %}
{% endif %}

course_discovery/apps/publisher/templates/publisher/course_run_detail/_edit_warning.html
{% load i18n %}

<div id="editCourseRun" class="modal">
    <div class="modal-content">
        <h2 class="hd-2 emphasized">
            <span class="icon fa fa-exclamation-triangle" aria-hidden="true"></span> {% trans "CAUTION" %}
        </h2>
        <span class="sr-only">CAUTION</span>
        <p>
<!-- Is "tasawer" in line 12 correct? -->
            {% blocktrans trimmed with owner=course_run.course_run_state.owner_role reviewer_user='tasawer'%}
                The {{ current_team_name }} is currently reviewing this course run. If you edit course run information, you might overwrite the team’s changes, and you will have to send the course run to the {{ team_name }} for review again.
            {% endblocktrans %}
        </p>
        <div class="actions">
            <a class="btn-cancel closeModal" href="#">{% trans "Cancel" %}</a>
            <a class="btn-brand btn-base btn-accept" type="button" href="{% url 'publisher:publisher_course_runs_edit' course_run.id %}">{% trans "Edit" %}</a>
        </div>
    </div>
</div>

course_discovery/apps/publisher/templates/publisher/course_run_detail/_instructor_profile.html
{% load i18n %}
{% load static %}

<div id="instructorProfileModal" class="modal">
    <div class="modal-content course-information">
        <div class="head" style="text-align: center;">
            <img class="image_url instructor-image" src="" alt="avatar">
            <a download href="" class="btn btn-download">
                <span class="icon fa fa-download" aria-hidden="true"></span>
                {% trans "Download" %}
            </a>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Name" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy full_name"></div>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Organization" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy organization"></div>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Title" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy position"></div>
        </div>

        <div class="info-item">
            <div class="heading">
                <a class="profile_url" target="_blank">{% trans "Profile URL "%}</a>
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy profile_url_copy hidden"></div>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Bio" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy bio pre"></div>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Social Links" %}</div>
            <div class="social-links"></div>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Major Works" %}
                {% include "publisher/course_run_detail/_clipboard.html" %}
            </div>
            <div class="copy major-works"></div>
        </div>

        <div class="info-item">
            <div class="heading">{% trans "Areas of Expertise" %}</div>
            <div class="areas-of-expertise"></div>
        </div>

        <div class="actions">
            <a class="btn-cancel closeModal" href="#">{% trans "Close" %}</a>
        </div>
    </div>
</div>

{% block extra_js %}
    <script src="{% static 'bower_components/clipboard/dist/clipboard.min.js' %}"></script>
{% endblock %}
    
{% block js_without_compress %}
    <script>
        new Clipboard(".btn-copy", {
            text: function(trigger) {
                return $(trigger).next('.copy').text().trim();
            }
        });
    </script>
{% endblock %}

course_discovery/apps/publisher/templates/publisher/course_run_detail/_seats.html
{% load i18n %}
<h3 class="hd-4 seat-set-hd">Seats</h3>
{% if course_run.non_credit_seats %}
<div class="seat-set">
    <table class="table">
            <tr>
              <th scope="col">{% trans "Enrollment Type" %}</th>
              <th scope="col">{% trans "Price" %}</th>
              <th scope="col">{% trans "Currency" %}</th>
              <th scope="col">{% trans "Upgrade Deadline (time in UTC)" %}</th>
            </tr>
            {% for seat in course_run.non_credit_seats %}
                    <tr>
                        <td>{{ seat.type}}</td>
                        <td>{{ seat.price}}</td>
                         <td>{{ seat.currency}}</td>
                        <td>{{ seat.upgrade_deadline }}</td>
                    </tr>
            {% endfor %}
    </table>
</div>
{% else %}
   {% trans "(Required) Not yet added" %}
{% endif %}

course_discovery/apps/publisher/templates/publisher/course_run_detail/_widgets.html
{% load i18n %}

<div class="course-widgets">
    {% if can_edit %}
        {% url 'publisher:publisher_course_runs_edit' pk=course_run.id as edit_page_url %}
        <a href="{% if add_warning_popup %}#{% else %}{{ edit_page_url }}{% endif %}" class="btn btn-neutral btn-courserun-edit">
            {% trans "EDIT" %}
        </a>
        <div class="clearfix"></div>
    {% endif %}
    <div class="approval-widget {% if not publisher_approval_widget_feature %}hidden{% endif %}">
        {% include 'publisher/_approval_widget.html' %}

        <div id="decline-comment" class="hidden clearfix">
            {% trans 'Reason for declining preview' as decline_reason %}
            {% trans 'Submit' as submit %}
            {% include 'publisher/comments/add_auth_comments.html' with comment_type='decline_preview' box_label=decline_reason btn_label=submit %}
        </div>
        {% include 'publisher/course_run_detail/_preview_accept_popup.html' %}

        {% if add_warning_popup %}
            {% include 'publisher/course_run_detail/_edit_warning.html' %}
        {% endif %}
    </div>
</div>