course_discovery/apps/publisher/api/urls.py
""" Publisher API URLs. """
from django.conf.urls import include, url

from course_discovery.apps.publisher.api.views import (
    AcceptAllRevisionView, ChangeCourseRunStateView, ChangeCourseStateView, CourseRevisionDetailView,
    CourseRoleAssignmentView, CoursesAutoComplete, OrganizationGroupUserView, RevertCourseRevisionView,
    UpdateCourseRunView
)

urlpatterns = [
    url(r'^course_role_assignments/(?P<pk>\d+)/$', CourseRoleAssignmentView.as_view(), name='course_role_assignments'),
    url(r'^admins/organizations/(?P<pk>\d+)/users/$', OrganizationGroupUserView.as_view(),
        name='organization_group_users'),
    url(r'^course_state/(?P<pk>\d+)/$', ChangeCourseStateView.as_view(), name='change_course_state'),
    url(r'^course_runs/(?P<pk>\d+)/$', UpdateCourseRunView.as_view(), name='update_course_run'),
    url(r'^course_revisions/(?P<history_id>\d+)/$', CourseRevisionDetailView.as_view(), name='course_revisions'),
    url(r'^course_run_state/(?P<pk>\d+)/$', ChangeCourseRunStateView.as_view(), name='change_course_run_state'),
    url(
        r'^course/revision/(?P<history_id>\d+)/revert/$',
        RevertCourseRevisionView.as_view(), name='course_revision_revert'
    ),
    url(r'^course-autocomplete/$', CoursesAutoComplete.as_view(), name='course-autocomplete'),
    url(
        r'^course/revision/(?P<history_id>\d+)/accept_revision/$',
        AcceptAllRevisionView.as_view(), name='accept_all_revision'
    ),
    url(r'^v1/', include('course_discovery.apps.publisher.api.v1.urls', namespace='v1')),
]

course_discovery/apps/publisher/api/v1/urls.py
from rest_framework.routers import DefaultRouter

from .views import CourseRunViewSet

router = DefaultRouter()
router.register(r'course_runs', CourseRunViewSet, base_name='course_run')
urlpatterns = router.urls

course_discovery/apps/publisher/urls.py
from django.conf.urls import include, url

from course_discovery.apps.publisher import views

urlpatterns = [
    url(r'^$', views.CourseRunListView.as_view(), name='publisher_dashboard'),
    url(r'^admin/importcourses/$', views.AdminImportCourse.as_view(), name='publisher_admin_import_course'),
    url(r'^api/', include('course_discovery.apps.publisher.api.urls', namespace='api')),
    url(r'^courses/$', views.CourseListView.as_view(), name='publisher_courses'),
    url(r'^courses/new/$', views.CreateCourseView.as_view(), name='publisher_courses_new'),
    url(r'^courses/(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='publisher_course_detail'),
    url(r'^courses/(?P<pk>\d+)/edit/$', views.CourseEditView.as_view(), name='publisher_courses_edit'),
    url(
        r'^courses/(?P<parent_course_id>\d+)/course_runs/new/$',
        views.CreateCourseRunView.as_view(),
        name='publisher_course_runs_new'
    ),
    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
    url(r'^course_runs/(?P<pk>\d+)/edit/$', views.CourseRunEditView.as_view(), name='publisher_course_runs_edit'),
    url(
        r'^course_runs/new/$',
        views.CreateRunFromDashboardView.as_view(),
        name='publisher_create_run_from_dashboard'
    ),
    url(
        r'^user/toggle/email_settings/$',
        views.ToggleEmailNotification.as_view(),
        name='publisher_toggle_email_settings'
    ),
    url(r'^courses/(?P<pk>\d+)/revisions/(?P<revision_id>\d+)/$', views.CourseRevisionView.as_view(),
        name='publisher_course_revision'),
    url(r'^email_preview/$', views.EmailPreviewView.as_view(), name='email_preview'),
]

course_discovery/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog

from course_discovery.apps.api.views import SwaggerSchemaView
from course_discovery.apps.core import views as core_views
from course_discovery.apps.course_metadata.views import QueryPreviewView

admin.site.site_header = _('Discovery Service Administration')
admin.site.site_title = admin.site.site_header
admin.autodiscover()

urlpatterns = auth_urlpatterns + [
    url(r'^admin/course_metadata/', include('course_discovery.apps.course_metadata.urls', namespace='admin_metadata')),
    url(r'^admin/core/', include('course_discovery.apps.core.urls', namespace='admin_core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('course_discovery.apps.api.urls', namespace='api')),
    # Use the same auth views for all logins, including those originating from the browseable API.
    url(r'^api-auth/', include(auth_urlpatterns, namespace='rest_framework')),
    url(r'^api-docs/', SwaggerSchemaView.as_view(), name='api_docs'),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^health/$', core_views.health, name='health'),
    url('^$', QueryPreviewView.as_view()),
    url(r'^publisher/', include('course_discovery.apps.publisher.urls', namespace='publisher')),
    url(r'^journal/', include('course_discovery.apps.journal.urls', namespace='journal')),
    url(
        r'^publisher/comments/', include(
            'course_discovery.apps.publisher_comments.urls', namespace='publisher_comments'
        )
    ),
    url(r'^language-tags/', include('course_discovery.apps.ietf_language_tags.urls', namespace='language_tags')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
]

# edx-drf-extensions csrf app
urlpatterns += [
    url(r'', include('csrf.urls')),
]

# Add the catalog extension urls if edx_catalog_extensions is installed.
if 'course_discovery.apps.edx_catalog_extensions' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^extensions/', include('course_discovery.apps.edx_catalog_extensions.urls', namespace='extensions'))
    )

if settings.DEBUG:  # pragma: no cover
    # We need this url pattern to serve user uploaded assets according to
    # https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    # This was modified to use LOCAL_MEDIA_URL to be able to server static files to external services like edx-mktg
    urlpatterns += static(settings.LOCAL_DISCOVERY_MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar

        urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

course_discovery/apps/publisher/api/v1/views.py
import logging
from collections import OrderedDict
from datetime import date

from edx_rest_api_client.client import EdxRestApiClient
from edx_rest_framework_extensions.auth.jwt.authentication import JwtAuthentication
from rest_framework import permissions, serializers, status, viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from slumber.exceptions import SlumberBaseException

from course_discovery.apps.core.utils import serialize_datetime
from course_discovery.apps.course_metadata.models import CourseEntitlement as DiscoveryCourseEntitlement
from course_discovery.apps.course_metadata.models import CourseRun as DiscoveryCourseRun
from course_discovery.apps.course_metadata.models import Seat as DiscoverySeat
from course_discovery.apps.course_metadata.models import Course, SeatType, Video
from course_discovery.apps.publisher.api.utils import (
    serialize_entitlement_for_ecommerce_api, serialize_seat_for_ecommerce_api
)
from course_discovery.apps.publisher.models import CourseRun, Seat
from course_discovery.apps.publisher.studio_api_utils import StudioAPI
from course_discovery.apps.publisher.utils import get_course_key

logger = logging.getLogger(__name__)


class CourseRunViewSet(viewsets.GenericViewSet):
    authentication_classes = (JwtAuthentication, SessionAuthentication,)
    queryset = CourseRun.objects.all()
    # NOTE: We intentionally use a basic serializer here since there is nothing, yet, to return.
    serializer_class = serializers.Serializer
    permission_classes = (permissions.IsAdminUser,)

    PUBLICATION_SUCCESS_STATUS = 'SUCCESS'

    @detail_route(methods=['post'])
    def publish(self, request, pk=None):
        course_run = self.get_object()
        partner = request.site.partner

        publication_status = {}

        try:
            publication_status['studio'] = self.publish_to_studio(partner, course_run)
            publication_status['discovery'] = self.publish_to_discovery(partner, course_run)
            # Publish to ecommerce last because it needs the just-created UUID from discovery
            publication_status['ecommerce'] = self.publish_to_ecommerce(partner, course_run)
        except SlumberBaseException as ex:
            logger.exception('Failed to publish course run [%s]!', pk)
            content = getattr(ex, 'content', None)
            if content:
                logger.error(content)
            raise

        status_code = status.HTTP_200_OK
        for _status in publication_status.values():
            if not _status.startswith(self.PUBLICATION_SUCCESS_STATUS):
                status_code = status.HTTP_502_BAD_GATEWAY
                break
        if status_code == status.HTTP_200_OK:
            logger.info(
                'Published course run with id: [%d] lms_course_id: [%s], user: [%s], date: [%s]',
                course_run.id,
                course_run.lms_course_id,
                request.user,
                date.today()
            )
        return Response(publication_status, status=status_code)

    def publish_to_studio(self, partner, course_run):
        api = StudioAPI(partner.studio_api_client)

        try:
            api.push_to_studio(course_run)
            return self.PUBLICATION_SUCCESS_STATUS
        except SlumberBaseException as ex:
            content = ex.content.decode('utf8')
            logger.exception('Failed to publish course run [%d] to Studio! Error was: [%s]', course_run.pk, content)
            return 'FAILED: ' + content
        except Exception as ex:  # pylint: disable=broad-except
            logger.exception('Failed to publish course run [%d] to Studio!', course_run.pk)
            return 'FAILED: ' + str(ex)

    def publish_to_ecommerce(self, partner, course_run):
        course_key = get_course_key(course_run.course)
        discovery_course = Course.objects.get(partner=partner, key=course_key)

        api = EdxRestApiClient(partner.ecommerce_api_url, jwt=partner.access_token)
        data = {
            'id': course_run.lms_course_id,
            'uuid': str(discovery_course.uuid),
            'name': course_run.title_override or course_run.course.title,
            'verification_deadline': serialize_datetime(course_run.end_date_temporary),
        }

        # NOTE: We only order here to aid testing. The E-Commerce API does NOT care about ordering.
        products = [serialize_seat_for_ecommerce_api(seat) for seat in
                    course_run.seats.exclude(type=Seat.CREDIT).order_by('created')]
        products.extend([serialize_entitlement_for_ecommerce_api(entitlement) for entitlement in
                         course_run.course.entitlements.order_by('created')])
        data['products'] = products

        try:
            api.publication.post(data)
            return self.PUBLICATION_SUCCESS_STATUS
        except SlumberBaseException as ex:
            content = ex.content.decode('utf8')
            logger.exception('Failed to publish course run [%d] to E-Commerce! Error was: [%s]', course_run.pk, content)
            return 'FAILED: ' + content

    def publish_to_discovery(self, partner, course_run):
        publisher_course = course_run.course
        course_key = get_course_key(publisher_course)

        video = None
        if publisher_course.video_link:
            video, __ = Video.objects.get_or_create(src=publisher_course.video_link)

        defaults = {
            'title': publisher_course.title,
            'short_description': publisher_course.short_description,
            'full_description': publisher_course.full_description,
            'level_type': publisher_course.level_type,
            'video': video,
            'outcome': publisher_course.expected_learnings,
            'prerequisites_raw': publisher_course.prerequisites,
            'syllabus_raw': publisher_course.syllabus,
            'additional_information': publisher_course.additional_information,
            'faq': publisher_course.faq,
            'learner_testimonials': publisher_course.learner_testimonial,
        }
        discovery_course, created = Course.objects.update_or_create(partner=partner, key=course_key, defaults=defaults)
        discovery_course.image.save(publisher_course.image.name, publisher_course.image.file)
        discovery_course.authoring_organizations.add(*publisher_course.organizations.all())

        subjects = [subject for subject in [
            publisher_course.primary_subject,
            publisher_course.secondary_subject,
            publisher_course.tertiary_subject
        ] if subject]
        subjects = list(OrderedDict.fromkeys(subjects))
        discovery_course.subjects.clear()
        discovery_course.subjects.add(*subjects)

        defaults = {
            'start': course_run.start_date_temporary,
            'end': course_run.end_date_temporary,
            'pacing_type': course_run.pacing_type_temporary,
            'title_override': course_run.title_override,
            'min_effort': course_run.min_effort,
            'max_effort': course_run.max_effort,
            'language': course_run.language,
            'weeks_to_complete': course_run.length,
            'has_ofac_restrictions': course_run.has_ofac_restrictions
        }
        discovery_course_run, __ = DiscoveryCourseRun.objects.update_or_create(
            course=discovery_course,
            key=course_run.lms_course_id,
            defaults=defaults
        )
        discovery_course_run.transcript_languages.add(*course_run.transcript_languages.all())
        discovery_course_run.staff.clear()
        discovery_course_run.staff.add(*course_run.staff.all())

        for entitlement in publisher_course.entitlements.all():
            DiscoveryCourseEntitlement.objects.update_or_create(
                course=discovery_course,
                mode=SeatType.objects.get(slug=entitlement.mode),
                defaults={
                    'partner': partner,
                    'price': entitlement.price,
                    'currency': entitlement.currency,
                }
            )

        for seat in course_run.seats.exclude(type=Seat.CREDIT).order_by('created'):
            DiscoverySeat.objects.update_or_create(
                course_run=discovery_course_run,
                type=seat.type,
                currency=seat.currency,
                defaults={
                    'price': seat.price,
                    'upgrade_deadline': seat.calculated_upgrade_deadline,
                }
            )
            if seat.masters_track:
                DiscoverySeat.objects.update_or_create(
                    course_run=discovery_course_run,
                    type=DiscoverySeat.MASTERS,
                    currency=seat.currency,
                    defaults={
                        'price': seat.price,
                        'upgrade_deadline': seat.calculated_upgrade_deadline,
                    }
                )

        if created:
            discovery_course.canonical_course_run = discovery_course_run
            discovery_course.save()

        return self.PUBLICATION_SUCCESS_STATUS

course_discovery/apps/publisher/templates/publisher/dashboard/_in_preview.html
{% load i18n %}
{% if preview_count == 0 %}
    <div class="empty-courserun-text">{% trans "No course runs currently have an About page preview available for course team review." %}</div>
{% else %}
    <p>
        {% trans "About page previews for the following course runs are available for course team review. After the course team approves the preview, the edX publisher will publish the About page for the course run on edx.org. The course team will receive an email message when the About page has been published." %}
    </p>
    <div class="table-view">
        <table class="data-table-preview display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th role="button">
                        {% trans "Course Name" %}
                    </th>
                    <th role="button">
                        {% trans "Organization" %}
                    </th>
                    <th role="button">
                        {% trans "Status" %}
                    </th>
                    <th>
                        {% trans "Modified" %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for course_run in preview_course_runs %}
                    <tr>
                        <td id="course-title-{{ course_run.title }}">
                            <a href="{% url 'publisher:publisher_course_run_detail' course_run.id %}">{{ course_run.title }}</a>
                            <br>
                            <a target="_blank" href="{{ course_run.preview_url }}">{{ course_run.preview_url }}</a>
                        </td>
                        <td>
                        {{ course_run.course.organization_name }}
                        </td>
                        <td data-order="{{ course_run.owner_role_modified|date:"Y-m-d" }}" >
                            {% if course_run.course_run_state.preview_accepted %}
                                {% trans "Approved since " %}
                            {% elif course_run.preview_declined and course_run.owner_role_is_publisher %}
                                {% trans "Declined since " %}
                            {% elif not course_run.preview_url %}
                                {% trans "Preview Requested since " %}
                            {% else %}
                                {% trans "In Review since " %}
                            {% endif %}
                            {{ course_run.owner_role_modified }}
                        </td>
                        <td data-order="{{ course_run.modified|date:"Y-m-d" }}">
                            {{ course_run.modified }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

course_discovery/apps/publisher/templates/publisher/dashboard/_in_progress.html
{% load i18n %}
{% if in_progress_count == 0 %}
    <div class="empty-courserun-text">{% trans "No About pages for any course runs are currently in development." %}</div>
{% else %}
    <table class="data-table-in-progress display" cellspacing="0" width="100%">
        <div class="filters">
            <strong>{% trans "Filter by" %}:</strong>
            <button type="button" class="btn-neutral btn-small btn-filter active" data-filter-column="-1">{% trans "All" %}
                <span class="filter-count">{{ in_progress_count }}</span>
            </button>
            <button type="button" class="btn-neutral btn-small btn-filter" data-search-value="{{ course_team_status }}" data-filter-column="4">{% trans "With Course Team" %}
                <span class="filter-count">{{ course_team_count }}</span>
            </button>
            <button type="button" class="btn-neutral btn-small btn-filter" data-search-value="{{ internal_user_status }}" data-filter-column="5">{% trans "With" %} {{ site_name }}
                <span class="filter-count">{{ internal_user_count }}</span>
            </button>
        </div>
        <thead>
            <tr>
                <th role="button">
                    {% trans "Course Name" %}
                </th>
                <th role="button">
                    {% trans "Course Number" %}
                </th>
                <th role="button">
                    {% trans "Organization" %}
                </th>
                <th role="button">
                    {% trans "Modified" %}
                </th>
                <th role="button">
                    {% trans "Course Team" %}
                </th>
                <th role="button">
                    {{ site_name }}
                </th>
                <th role="button">
                    {% trans "Last Handoff" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for course_run in in_progress_course_runs %}
                <tr>
                    <td>
                        <a href="{% url 'publisher:publisher_course_run_detail' course_run.id %}">
                            {{ course_run.title }}
                        </a>
                    </td>
                    <td>{{ course_run.number }}</td>
                    <td>{{ course_run.course.organization_name }}</td>
                    <td>{{ course_run.modified|date:"Y-m-d" }}</td>
                    <td>{{ course_run.course_team_status }}</td>
                    <td>{{ course_run.internal_user_status }}</td>
                    <td>{{ course_run.owner_role_last_modified }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

course_discovery/apps/publisher/templates/publisher/dashboard/_published.html
{% load i18n %}
{% if published_count == 0 %}
    <div class="empty-courserun-text">{% trans "No About pages have been published yet." %}</div>
{% else %}
    <p>
        {% blocktrans trimmed %}
            About pages for the following course runs have been published in the past {{ default_published_days }} days.
        {% endblocktrans %}
    </p>
    <table class="data-table-published display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th role="button">
                    {% trans "Course Name" %}
                </th>
                <th role="button">
                    {% trans "Course Number" %}
                </th>
                <th role="button">
                    {% trans "Organization" %}
                </th>
                <th role="button">
                    {% trans "Published Date" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for course_run in published_course_runs %}
                <tr>
                    <td>
                        <a href="{% url 'publisher:publisher_course_run_detail' course_run.id %}">{{ course_run.title }}</a>
                    </td>
                    <td>
                        {{ course_run.number }}
                    </td>
                    <td>
                        {{ course_run.course.organization_name }}
                    </td>
                    <td>
                        {{ course_run.course_run_state.modified|date:"Y-m-d" }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

course_discovery/apps/publisher/templates/publisher/dashboard/_studio_requests.html
{% load i18n %}

{% if studio_count > 0 %}
    <p>{% trans "The following courses are ready for a Studio URL." %}</p>
        <div class="studio-instance-success depth depth-0">
          <p class="copy-meta"></p>
        </div>
        <div class="alert alert-error alert-slim studio-instance-error hidden">
            <div class="alert-message">
                <p class="copy"></p>
            </div>
        </div>
    <div class="table-view">
        <table class="data-table-studio display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th role="button">
                        {% trans "Course Name" %}
                    </th>
                    <th role="button">
                        {% trans "Organization" %}
                    </th>
                    <th role="button">
                        {% trans "Modified" %}
                    </th>
                    <th role="button">
                        {% trans "Course Number" %}
                    </th>
                    <th id="column-title" role="button">
                        {% trans "Studio Course Run Key" %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for course_run in studio_request_courses %}
                    <tr>
                        {% url 'publisher:publisher_course_run_detail' course_run.id as run_page_url %}
                            <td id="course-title-{{ course_run.title }}">
                                <a href="{{ run_page_url }}" id="course-title">{{ course_run.title }}</a>
                            </td>
                            <td>
                                {{ course_run.course.organization_name }}
                            </td>
                            <td id="course-modified">
                                 {{ course_run.modified|date:"Y-m-d" }}
                            </td>
                            <td>
                                {{ course_run.number }}
                            </td>
                            <td class="form-group">
                                <input type="text" class="field-input input-text small" aria-labelledby="course-title-{{ course_run.title }} column-title" />
                                <button data-update-course-key-url="{% url 'publisher:api:update_course_run' course_run.id %}" class="btn-inline btn-add-course-key">{% trans "Add" %}</button>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% else %}
    <div class="empty-courserun-text">{% trans "No courses are currently ready for a Studio URL." %}</div>
{% endif %}